
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_OPEN_AUTH = "MODAL_OPEN_AUTH";
export const MODAL_OPEN_MEALCOST = "MODAL_OPEN_MEALCOST";
export const MODAL_OPEN_LOGIN = "MODAL_OPEN_LOGIN";
export const MODAL_OPEN_REGISTER = "MODAL_OPEN_REGISTER";


export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";

export const EMPLOYEE_FETCH_REQUESTED = "EMPLOYEE_FETCH_REQUESTED";
export const EMPLOYEE_FETCH_SUCCEEDED = "EMPLOYEE_FETCH_SUCCEEDED";
export const EMPLOYEE_FETCH_FAILED = "EMPLOYEE_FETCH_FAILED";

export const EMPLOYEE_ADD_REQUESTED = "EMPLOYEE_ADD_REQUESTED";
export const EMPLOYEE_ADD_SUCCEEDED = "EMPLOYEE_ADD_SUCCEEDED";
export const EMPLOYEE_ADD_FAILED = "EMPLOYEE_ADD_FAILED";

export const EMPLOYEE_UPDATE_REQUESTED = "EMPLOYEE_UPDATE_REQUESTED";
export const EMPLOYEE_UPDATE_SUCCEEDED = "EMPLOYEE_UPDATE_SUCCEEDED";
export const EMPLOYEE_UPDATE_FAILED = "EMPLOYEE_UPDATE_FAILED";

export const EMPLOYEE_DELETE_REQUESTED = "EMPLOYEE_DELETE_REQUESTED";
export const EMPLOYEE_DELETE_SUCCEEDED = "EMPLOYEE_DELETE_SUCCEEDED";
export const EMPLOYEE_DELETE_FAILED = "EMPLOYEE_DELETE_FAILED";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_REQUESTED_SUCCEEDED = "LOGIN_REQUESTED_SUCCEEDED";
export const LOGIN_REQUESTED_FAILED = "LOGIN_REQUESTED_FAILED";

export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_REQUESTED_SUCCEEDED = "LOGOUT_REQUESTED_SUCCEEDED";
export const LOGOUT_REQUESTED_FAILED = "LOGOUT_REQUESTED_FAILED";

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

export const USER_SELECTED = "USER_SELECTED";
export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";

export const USER_ADD_REQUESTED = "USER_ADD_REQUESTED";
export const USER_ADD_SUCCEEDED = "USER_ADD_SUCCEEDED";
export const USER_ADD_FAILED = "USER_ADD_FAILED";

export const USER_UPDATE_REQUESTED = "USER_UPDATE_REQUESTED";
export const USER_UPDATE_SUCCEEDED = "USER_UPDATE_SUCCEEDED";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";

export const USER_DELETE_REQUESTED = "USER_DELETE_REQUESTED";
export const USER_DELETE_SUCCEEDED = "USER_DELETE_SUCCEEDED";
export const USER_DELETE_FAILED = "USER_DELETE_FAILED";



export const MEALCOST_SELECTED = "MEALCOST_SELECTED";

export const MEALCOST_FETCH_REQUESTED = "MEALCOST_FETCH_REQUESTED";
export const MEALCOST_FETCH_SUCCEEDED = "MEALCOST_FETCH_SUCCEEDED";
export const MEALCOST_FETCH_FAILED = "MEALCOST_FETCH_FAILED";

export const MEALCOST_ADD_REQUESTED = "MEALCOST_ADD_REQUESTED";
export const MEALCOST_ADD_SUCCEEDED = "MEALCOST_ADD_SUCCEEDED";
export const MEALCOST_ADD_FAILED = "MEALCOST_ADD_FAILED";

export const MEALCOST_UPDATE_REQUESTED = "MEALCOST_UPDATE_REQUESTED";
export const MEALCOST_UPDATE_SUCCEEDED = "MEALCOST_UPDATE_SUCCEEDED";
export const MEALCOST_UPDATE_FAILED = "MEALCOST_UPDATE_FAILED";

export const MEALCOST_DELETE_REQUESTED = "MEALCOST_DELETE_REQUESTED";
export const MEALCOST_DELETE_SUCCEEDED = "MEALCOST_DELETE_SUCCEEDED";
export const MEALCOST_DELETE_FAILED = "MEALCOST_DELETE_FAILED";

